services:
  eshopwebmvc:
    image: ${DOCKER_REGISTRY-}eshopwebmvc
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    ports:
      - "5106:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - "sqlserver"
  eshoppublicapi:
    image: ${DOCKER_REGISTRY-}eshoppublicapi
    build:
      context: .
      dockerfile: src/PublicApi/Dockerfile
    ports:
      - "5200:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - "sqlserver"
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=@someThingComplicated1234
      - ACCEPT_EULA=Y
  
  traffic-simulator:
    build:
      context: ./src/traffic-simulator
      dockerfile: Dockerfile
    environment:
      - APP_URL=http://eshopwebmvc:8080
    depends_on:
      - eshopwebmvc

